# Stage 1: Install PHP dependencies & generate Wayfinder route types
# The Wayfinder Vite plugin calls `php artisan wayfinder:generate` during build,
# so we must generate these TypeScript types in a PHP stage before the Node build.
FROM php:8.3-fpm-alpine AS php-deps

# Install system dependencies and PHP extensions
RUN apk add --no-cache \
    postgresql-dev \
    libzip-dev \
    zip \
    unzip \
    git \
    curl \
    oniguruma-dev \
    linux-headers \
    && docker-php-ext-install pdo pdo_pgsql pgsql mbstring zip pcntl bcmath opcache

# Install Composer
COPY --from=composer:2.7 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

# Copy application files
COPY . .

# Bootstrap a minimal .env BEFORE composer install, because the post-autoload-dump
# hook runs `php artisan package:discover` which bootstraps Laravel — including the
# Reverb broadcaster that requires Pusher credentials to instantiate.
RUN cp .env.example .env \
    && php -r "echo 'APP_KEY=base64:' . base64_encode(random_bytes(32)) . PHP_EOL;" >> .env \
    && echo "REVERB_APP_ID=build-dummy" >> .env \
    && echo "REVERB_APP_KEY=build-dummy" >> .env \
    && echo "REVERB_APP_SECRET=build-dummy" >> .env \
    && touch database/database.sqlite

# Install PHP dependencies (package:discover now has a valid .env)
RUN composer install --no-dev --optimize-autoloader --no-interaction --no-progress

# Generate Wayfinder TypeScript types (routes + form actions)
RUN php artisan wayfinder:generate --with-form


# Stage 2: Build Node.js assets
FROM node:22-alpine AS node-builder

WORKDIR /app

# Copy package management files
COPY package.json pnpm-workspace.yaml* package-lock.json* pnpm-lock.yaml* yarn.lock* ./

# Install dependencies based on the lock file present
RUN if [ -f pnpm-lock.yaml ]; then \
        corepack enable pnpm && pnpm install --frozen-lockfile; \
    elif [ -f yarn.lock ]; then \
        yarn install --frozen-lockfile; \
    else \
        npm ci; \
    fi

# Copy the rest of the application
COPY . .

# Copy generated Wayfinder types from php-deps (these are gitignored, so not in source)
COPY --from=php-deps /var/www/html/resources/js/actions ./resources/js/actions
COPY --from=php-deps /var/www/html/resources/js/routes ./resources/js/routes
COPY --from=php-deps /var/www/html/resources/js/wayfinder ./resources/js/wayfinder

# VITE_* vars are inlined into the JS bundle at build time — pass them as build args
ARG VITE_REVERB_APP_KEY
ARG VITE_REVERB_HOST
ARG VITE_REVERB_PORT
ARG VITE_APP_NAME

# Tell vite.config.ts to skip the wayfinder plugin (types are pre-generated by php-deps)
ENV DOCKER_BUILD=true \
    VITE_REVERB_APP_KEY=${VITE_REVERB_APP_KEY} \
    VITE_REVERB_HOST=${VITE_REVERB_HOST} \
    VITE_REVERB_PORT=${VITE_REVERB_PORT} \
    VITE_APP_NAME=${VITE_APP_NAME}

# Build Vite assets
RUN if [ -f pnpm-lock.yaml ]; then \
        corepack enable pnpm && pnpm run build; \
    elif [ -f yarn.lock ]; then \
        yarn build; \
    else \
        npm run build; \
    fi


# Stage 3: Build PHP Application
FROM php:8.3-fpm-alpine AS app

# Install system dependencies and PHP extensions
RUN apk add --no-cache \
    postgresql-dev \
    libzip-dev \
    zip \
    unzip \
    git \
    curl \
    oniguruma-dev \
    linux-headers \
    && docker-php-ext-install pdo pdo_pgsql pgsql mbstring zip pcntl bcmath opcache

# Set working directory
WORKDIR /var/www/html

# Copy application files (excluding those in .dockerignore)
COPY . .

# Copy built frontend assets from node-builder
COPY --from=node-builder /app/public/build ./public/build

# Reuse pre-installed vendor directory from php-deps stage
COPY --from=php-deps /var/www/html/vendor ./vendor

# Set permissions for Laravel
RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache

# Copy entrypoint script
COPY docker/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

# Use entrypoint to run migrations and cache
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

# Default command for the container
CMD ["php-fpm"]


# Stage 4: Build Nginx web server
FROM nginx:alpine AS web

# Copy Nginx config
COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf

# Copy public directory with built assets
COPY --from=app /var/www/html/public /var/www/html/public
